### ISSUE TITLE
Share lemonbar and popups?

### ISSUE THREAD

**Issue by Anachron** [Wulfre/dotfiles#1]
https://github.com/Wulfre/dotfiles/blob/master/wm/.config/bspwm/bspwmrc#L40-L46

These popups/lemonbar-configs are not in your repo. Do you mind sharing them too?

**Comment by Wulfre** [comment]
They should be included under the `\wm` directory. I might need to restructure that to make it a bit more clear.

**Comment by Wulfre** [comment]
I restructured like I said. They are now included in `lemonbar--home/.config/lemonbar`.
